import streamlit as st
import pandas as pd
import plotly.express as px
import sqlite3

# --- PAGE CONFIG ---
st.set_page_config(page_title="CFO Dashboard", layout="wide")

# --- DATABASE CONNECTION (SQLITE) ---
# Connects directly to the file generated by data_gen.py
def get_connection():
    return sqlite3.connect("financial_db.sqlite")

@st.cache_data
def get_financial_data():
    """Fetch Profitability & Margin Analysis"""
    conn = get_connection()
    query = """
    SELECT 
        p.productLine, 
        SUM(od.quantityOrdered * od.priceEach) AS Revenue,
        SUM(od.quantityOrdered * p.buyPrice) AS CostOfGoodsSold,
        SUM(od.quantityOrdered * (od.priceEach - p.buyPrice)) AS GrossProfit
    FROM products p
    JOIN orderdetails od ON p.productCode = od.productCode
    JOIN orders o ON od.orderNumber = o.orderNumber
    WHERE o.status = 'Shipped'
    GROUP BY p.productLine;
    """
    df = pd.read_sql(query, conn)
    conn.close()
    return df

# --- DASHBOARD LAYOUT ---
st.title("📊 Financial Performance Executive Summary")
st.markdown("Financial health overview focusing on **Profitability**, **Margins**, and **Revenue Composition**.")

# Load Data
try:
    df = get_financial_data()
    
    # 1. TOP ROW KPIs
    total_revenue = df['Revenue'].sum()
    total_profit = df['GrossProfit'].sum()
    total_margin = (total_profit / total_revenue) * 100 if total_revenue > 0 else 0

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Revenue", f"${total_revenue:,.0f}")
    col2.metric("Gross Profit", f"${total_profit:,.0f}")
    col3.metric("Overall Margin", f"{total_margin:.1f}%")

    st.divider()

    # 2. CHARTS ROW
    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        st.subheader("Profitability by Product Line")
        df['Margin %'] = (df['GrossProfit'] / df['Revenue']) * 100
        fig = px.bar(df, x='productLine', y='Revenue', title="Revenue vs. Margin %",
                     hover_data=['GrossProfit', 'Margin %'], color='Revenue')
        st.plotly_chart(fig, use_container_width=True)

    with col_chart2:
        st.subheader("Profit Contribution")
        fig2 = px.pie(df, values='GrossProfit', names='productLine', hole=0.4,
                      title="Share of Total Gross Profit")
        st.plotly_chart(fig2, use_container_width=True)

except Exception as e:
    st.error(f"Error loading database. Did you run data_gen.py? Error: {e}")